### ISSUE TITLE
how do i get a group post url? someone explain

### ISSUE THREAD

**Issue by snowystraw728** [Kop3kns/xuid-Scraper#3]

**Comment by Kop3kns** [comment]
When you open a group post with a http packet capture like fiddler there will be a comment url with a continuation token. Then when inputted the program will scrape all of the comment xuids in the post and save it to a file. After scraping the xuids in the group post it will scrape all of the friends of the xuids scraped. btw fiddler is patched rn so i have to implement a patch

**Comment by Kop3kns** [comment]
Fixed
